# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
- task: UseDotNet@2
  displayName: 'Install .NET Core runtime'
  inputs:
    packageType: "runtime"
    version: "8.0.6"
- task: UseDotNet@2
  displayName: "Using DotNet@2"
  inputs:
    packageType: "sdk"
    version: "8.0.302"
- task: DotNetCoreCLI@2
  displayName: "Install dotnet format"
  inputs:
    command: "custom"
    custom: "tool"
    arguments: "update -g dotnet-format"

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'dotnet format --verify-no-changes --verbosity diagnostic'
    ignoreLASTEXITCODE: true
    pwsh: true 
    workingDirectory: backend
